-- CIT 406: University Course Registration and Department Management System
-- Group members: Bishnu Bahadur GC and Swastika Poudel
-- Run this file first in a fresh Supabase PostgreSQL database, then seed.sql.
-- Tables use public so they appear in Supabase Table Editor and Schema Visualizer.

CREATE TABLE public.department (
    department_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name varchar(100) NOT NULL,
    office_location varchar(100),
    phone_number varchar(30)
);

CREATE TABLE public.semester (
    semester_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_name varchar(40) NOT NULL,
    academic_year integer NOT NULL CHECK (academic_year BETWEEN 2000 AND 2100),
    start_date date NOT NULL,
    end_date date NOT NULL,
    CONSTRAINT semester_dates_valid CHECK (end_date >= start_date)
);

CREATE TABLE public.classroom (
    classroom_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name varchar(100) NOT NULL,
    room_number varchar(20) NOT NULL,
    capacity integer NOT NULL CHECK (capacity > 0)
);

CREATE TABLE public.student (
    student_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(80) NOT NULL,
    last_name varchar(80) NOT NULL,
    email varchar(255) NOT NULL,
    phone varchar(30),
    date_of_birth date,
    department_id integer NOT NULL,
    CONSTRAINT student_department_fk FOREIGN KEY (department_id)
        REFERENCES public.department(department_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE public.instructor (
    instructor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(80) NOT NULL,
    last_name varchar(80) NOT NULL,
    email varchar(255) NOT NULL,
    phone varchar(30),
    department_id integer NOT NULL,
    CONSTRAINT instructor_department_fk FOREIGN KEY (department_id)
        REFERENCES public.department(department_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE public.course (
    course_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code varchar(30) NOT NULL,
    course_name varchar(150) NOT NULL,
    credit_hours integer NOT NULL CHECK (credit_hours BETWEEN 0 AND 12),
    description text,
    department_id integer NOT NULL,
    CONSTRAINT course_department_fk FOREIGN KEY (department_id)
        REFERENCES public.department(department_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE public.section (
    section_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_number varchar(20) NOT NULL,
    schedule text NOT NULL,
    maximum_capacity integer NOT NULL CHECK (maximum_capacity > 0),
    course_id integer NOT NULL,
    instructor_id integer NOT NULL,
    semester_id integer NOT NULL,
    classroom_id integer NOT NULL,
    CONSTRAINT section_course_fk FOREIGN KEY (course_id)
        REFERENCES public.course(course_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT section_instructor_fk FOREIGN KEY (instructor_id)
        REFERENCES public.instructor(instructor_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT section_semester_fk FOREIGN KEY (semester_id)
        REFERENCES public.semester(semester_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT section_classroom_fk FOREIGN KEY (classroom_id)
        REFERENCES public.classroom(classroom_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE public.enrollment (
    enrollment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL,
    section_id integer NOT NULL,
    enrollment_date date NOT NULL,
    enrollment_status varchar(20) NOT NULL
        CHECK (enrollment_status IN ('enrolled', 'completed', 'dropped')),
    grade varchar(5),
    CONSTRAINT enrollment_student_fk FOREIGN KEY (student_id)
        REFERENCES public.student(student_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT enrollment_section_fk FOREIGN KEY (section_id)
        REFERENCES public.section(section_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- No additional uniqueness rules are asserted for email, course code, room,
-- section number, or student/section: the approved ERD does not specify them.
-- Enrollment capacity and schedule conflicts require separate transactional rules.
